// ============================================================
// Seed Script  Populates initial data for development
// ============================================================

import { v4 as uuidv4 } from 'uuid';
import { writeCollection } from './fileStore';
import { hashPassword } from './password';
import {
  User,
  UserRole,
  Volunteer,
  Donor,
  Project,
  ProjectStatus,
  Donation,
  DonationType,
  OngEvent,
  EventStatus,
} from '../models';

function pastDate(daysAgo: number): string {
  const d = new Date();
  d.setDate(d.getDate() - daysAgo);
  return d.toISOString();
}

function futureDate(daysAhead: number): string {
  const d = new Date();
  d.setDate(d.getDate() + daysAhead);
  return d.toISOString();
}

export async function seed(): Promise<void> {
  console.log('\ud83c\udf31 Seeding database...');

  // ---- Users ----
  const adminPassword = await hashPassword('admin123');
  const volunteerPassword = await hashPassword('voluntario123');
  const donorPassword = await hashPassword('doador123');

  const users: User[] = [
    {
      id: uuidv4(),
      name: 'Administrador CUFA',
      email: 'admin@cufape.org.br',
      password: adminPassword,
      role: UserRole.ADMIN,
      phone: '(81) 99999-0001',
      isActive: true,
      createdAt: pastDate(90),
      updatedAt: pastDate(90),
    },
    {
      id: uuidv4(),
      name: 'Maria Volunt\u00e1ria',
      email: 'maria@email.com',
      password: volunteerPassword,
      role: UserRole.VOLUNTEER,
      phone: '(81) 99999-0002',
      isActive: true,
      createdAt: pastDate(60),
      updatedAt: pastDate(60),
    },
    {
      id: uuidv4(),
      name: 'Jo\u00e3o Doador',
      email: 'joao@email.com',
      password: donorPassword,
      role: UserRole.DONOR,
      phone: '(81) 99999-0003',
      isActive: true,
      createdAt: pastDate(45),
      updatedAt: pastDate(45),
    },
    {
      id: uuidv4(),
      name: 'Ana Visitante',
      email: 'ana@email.com',
      password: await hashPassword('visitante123'),
      role: UserRole.VISITOR,
      phone: '(81) 99999-0004',
      isActive: true,
      createdAt: pastDate(30),
      updatedAt: pastDate(30),
    },
  ];

  // ---- Volunteers ----
  const volunteerIds = Array.from({ length: 8 }, () => uuidv4());
  const volunteers: Volunteer[] = [
    {
      id: volunteerIds[0],
      name: 'Maria Silva Santos',
      email: 'maria.silva@email.com',
      phone: '(81) 98765-1001',
      cpf: '123.456.789-01',
      birthDate: '1990-05-15',
      address: 'Rua da Aurora, 123',
      city: 'Recife',
      state: 'PE',
      zipCode: '50050-000',
      skills: ['Educa\u00e7\u00e3o', 'Comunica\u00e7\u00e3o', 'Lideran\u00e7a'],
      availability: 'Fins de semana',
      notes: 'Professora aposentada',
      isActive: true,
      createdAt: pastDate(80),
      updatedAt: pastDate(80),
    },
    {
      id: volunteerIds[1],
      name: 'Carlos Eduardo Lima',
      email: 'carlos.lima@email.com',
      phone: '(81) 98765-1002',
      cpf: '234.567.890-12',
      birthDate: '1985-08-22',
      address: 'Av. Boa Viagem, 456',
      city: 'Recife',
      state: 'PE',
      zipCode: '51020-000',
      skills: ['Sa\u00fade', 'Primeiros socorros'],
      availability: 'Segundas e quartas',
      isActive: true,
      createdAt: pastDate(70),
      updatedAt: pastDate(70),
    },
    {
      id: volunteerIds[2],
      name: 'Fernanda Oliveira',
      email: 'fernanda.o@email.com',
      phone: '(81) 98765-1003',
      cpf: '345.678.901-23',
      birthDate: '1995-12-03',
      address: 'Rua do Brum, 789',
      city: 'Recife',
      state: 'PE',
      zipCode: '50030-000',
      skills: ['Tecnologia', 'Design', 'Redes sociais'],
      availability: 'Integral',
      isActive: true,
      createdAt: pastDate(60),
      updatedAt: pastDate(60),
    },
    {
      id: volunteerIds[3],
      name: 'Roberto Almeida',
      email: 'roberto.a@email.com',
      phone: '(81) 98765-1004',
      cpf: '456.789.012-34',
      birthDate: '1988-03-17',
      address: 'Rua da Concord\u00e2ncia, 321',
      city: 'Olinda',
      state: 'PE',
      zipCode: '53020-000',
      skills: ['Log\u00edstica', 'Transporte', 'Organiza\u00e7\u00e3o'],
      availability: 'Fins de semana',
      isActive: true,
      createdAt: pastDate(50),
      updatedAt: pastDate(50),
    },
    {
      id: volunteerIds[4],
      name: 'Juliana Costa',
      email: 'juliana.c@email.com',
      phone: '(81) 98765-1005',
      cpf: '567.890.123-45',
      birthDate: '1992-07-28',
      address: 'Rua da Alegria, 654',
      city: 'Jaboat\u00e3o',
      state: 'PE',
      zipCode: '54080-000',
      skills: ['Psicologia', 'Atendimento'],
      availability: 'Ter\u00e7as e quintas',
      isActive: true,
      createdAt: pastDate(40),
      updatedAt: pastDate(40),
    },
    {
      id: volunteerIds[5],
      name: 'Pedro Henrique Souza',
      email: 'pedro.h@email.com',
      phone: '(81) 98765-1006',
      cpf: '678.901.234-56',
      birthDate: '1993-11-09',
      address: 'Av. Caxang\u00e1, 987',
      city: 'Recife',
      state: 'PE',
      zipCode: '50740-000',
      skills: ['Esportes', 'Recrea\u00e7\u00e3o'],
      availability: 'S\u00e1bados',
      isActive: true,
      createdAt: pastDate(30),
      updatedAt: pastDate(30),
    },
    {
      id: volunteerIds[6],
      name: 'Luciana Ferreira',
      email: 'luciana.f@email.com',
      phone: '(81) 98765-1007',
      cpf: '789.012.345-67',
      birthDate: '1987-01-25',
      address: 'Rua da Harmonia, 159',
      city: 'Recife',
      state: 'PE',
      zipCode: '52060-000',
      skills: ['Culin\u00e1ria', 'Nutri\u00e7\u00e3o'],
      availability: 'Quintas e sextas',
      isActive: false,
      createdAt: pastDate(20),
      updatedAt: pastDate(10),
    },
    {
      id: volunteerIds[7],
      name: 'Marcos Antonio Torres',
      email: 'marcos.t@email.com',
      phone: '(81) 98765-1008',
      cpf: '890.123.456-78',
      birthDate: '1991-06-14',
      address: 'Rua do Progresso, 753',
      city: 'Recife',
      state: 'PE',
      zipCode: '50070-000',
      skills: ['Constru\u00e7\u00e3o', 'El\u00e9trica', 'Hidr\u00e1ulica'],
      availability: 'Domingos',
      isActive: true,
      createdAt: pastDate(15),
      updatedAt: pastDate(15),
    },
  ];

  // ---- Donors ----
  const donorIds = Array.from({ length: 7 }, () => uuidv4());
  const donors: Donor[] = [
    {
      id: donorIds[0],
      name: 'Empresa ABC Ltda',
      email: 'contato@empresaabc.com.br',
      phone: '(81) 3333-0001',
      cnpj: '12.345.678/0001-01',
      type: 'company',
      address: 'Av. Agamenon Magalh\u00e3es, 1500',
      city: 'Recife',
      state: 'PE',
      notes: 'Parceira corporativa mensal',
      isActive: true,
      createdAt: pastDate(120),
      updatedAt: pastDate(5),
    },
    {
      id: donorIds[1],
      name: 'Jo\u00e3o Silva',
      email: 'joao.silva@email.com',
      phone: '(81) 99888-1001',
      cpf: '111.222.333-44',
      type: 'individual',
      city: 'Recife',
      state: 'PE',
      isActive: true,
      createdAt: pastDate(90),
      updatedAt: pastDate(10),
    },
    {
      id: donorIds[2],
      name: 'Supermercado Esperan\u00e7a',
      email: 'doacoes@supesperanca.com.br',
      phone: '(81) 3333-0002',
      cnpj: '23.456.789/0001-02',
      type: 'company',
      address: 'Rua do Com\u00e9rcio, 500',
      city: 'Recife',
      state: 'PE',
      notes: 'Doa\u00e7\u00f5es regulares de alimentos',
      isActive: true,
      createdAt: pastDate(80),
      updatedAt: pastDate(15),
    },
    {
      id: donorIds[3],
      name: 'Funda\u00e7\u00e3o XYZ',
      email: 'projetos@fundacaoxyz.org',
      phone: '(81) 3333-0003',
      cnpj: '34.567.890/0001-03',
      type: 'company',
      address: 'Av. Conde da Boa Vista, 800',
      city: 'Recife',
      state: 'PE',
      notes: 'Financiamento via editais sociais',
      isActive: true,
      createdAt: pastDate(60),
      updatedAt: pastDate(20),
    },
    {
      id: donorIds[4],
      name: 'Maria Fernanda Costa',
      email: 'maria.fc@email.com',
      phone: '(81) 99888-1002',
      cpf: '222.333.444-55',
      type: 'individual',
      city: 'Olinda',
      state: 'PE',
      isActive: true,
      createdAt: pastDate(50),
      updatedAt: pastDate(25),
    },
    {
      id: donorIds[5],
      name: 'Instituto Boa Vontade',
      email: 'contato@ibv.org.br',
      phone: '(81) 3333-0004',
      cnpj: '45.678.901/0001-04',
      type: 'company',
      address: 'Rua da Uni\u00e3o, 200',
      city: 'Recife',
      state: 'PE',
      isActive: true,
      createdAt: pastDate(45),
      updatedAt: pastDate(35),
    },
    {
      id: donorIds[6],
      name: 'Farm\u00e1cia Popular',
      email: 'social@farmaciapopular.com.br',
      phone: '(81) 3333-0005',
      cnpj: '56.789.012/0001-05',
      type: 'company',
      address: 'Rua do Bom Jesus, 100',
      city: 'Recife',
      state: 'PE',
      notes: 'Doa\u00e7\u00f5es de medicamentos',
      isActive: true,
      createdAt: pastDate(40),
      updatedAt: pastDate(40),
    },
  ];

  // ---- Projects ----
  const projectIds = Array.from({ length: 5 }, () => uuidv4());
  const projects: Project[] = [
    {
      id: projectIds[0],
      name: 'Educa\u00e7\u00e3o para Todos',
      description: 'Programa de refor\u00e7o escolar e alfabetiza\u00e7\u00e3o para crian\u00e7as e adultos das comunidades do Recife.',
      status: ProjectStatus.ACTIVE,
      startDate: pastDate(120),
      endDate: futureDate(240),
      budget: 50000,
      raised: 35000,
      coordinator: 'Maria Silva Santos',
      volunteerIds: [volunteerIds[0], volunteerIds[2], volunteerIds[4]],
      goals: ['Alfabetizar 100 adultos', 'Refor\u00e7o escolar para 200 crian\u00e7as', 'Formar 20 monitores'],
      category: 'Educa\u00e7\u00e3o',
      location: 'Centro Comunit\u00e1rio da CUFA - Recife',
      beneficiaries: 300,
      createdAt: pastDate(120),
      updatedAt: pastDate(5),
    },
    {
      id: projectIds[1],
      name: 'Sa\u00fade na Comunidade',
      description: 'A\u00e7\u00f5es preventivas de sa\u00fade incluindo consultas m\u00e9dicas, vacina\u00e7\u00e3o e orienta\u00e7\u00e3o sobre higiene.',
      status: ProjectStatus.ACTIVE,
      startDate: pastDate(90),
      endDate: futureDate(180),
      budget: 80000,
      raised: 55000,
      coordinator: 'Carlos Eduardo Lima',
      volunteerIds: [volunteerIds[1], volunteerIds[4]],
      goals: ['Atender 500 consultas', 'Campanha de vacina\u00e7\u00e3o', 'Palestras sobre sa\u00fade preventiva'],
      category: 'Sa\u00fade',
      location: 'Comunidades da Zona Norte - Recife',
      beneficiaries: 500,
      createdAt: pastDate(90),
      updatedAt: pastDate(3),
    },
    {
      id: projectIds[2],
      name: 'Horta Comunit\u00e1ria',
      description: 'Cria\u00e7\u00e3o e manuten\u00e7\u00e3o de hortas comunit\u00e1rias para alimenta\u00e7\u00e3o saud\u00e1vel e gera\u00e7\u00e3o de renda.',
      status: ProjectStatus.PLANNING,
      startDate: futureDate(30),
      budget: 15000,
      raised: 8000,
      coordinator: 'Fernanda Oliveira',
      volunteerIds: [volunteerIds[2], volunteerIds[6]],
      goals: ['Implantar 3 hortas comunit\u00e1rias', 'Capacitar 50 fam\u00edlias', 'Venda de excedentes'],
      category: 'Meio Ambiente',
      location: 'Comunidades de Olinda e Recife',
      beneficiaries: 150,
      createdAt: pastDate(30),
      updatedAt: pastDate(1),
    },
    {
      id: projectIds[3],
      name: 'Esporte para Vida',
      description: 'Programa esportivo para jovens em situa\u00e7\u00e3o de vulnerabilidade social nas favelas do Recife.',
      status: ProjectStatus.COMPLETED,
      startDate: pastDate(365),
      endDate: pastDate(30),
      budget: 40000,
      raised: 40000,
      coordinator: 'Pedro Henrique Souza',
      volunteerIds: [volunteerIds[5], volunteerIds[7]],
      goals: ['Atender 200 jovens', 'Torneio municipal', 'Bolsas esportivas'],
      category: 'Esporte',
      location: 'Gin\u00e1sio Comunit\u00e1rio - Ibura',
      beneficiaries: 200,
      createdAt: pastDate(365),
      updatedAt: pastDate(30),
    },
    {
      id: projectIds[4],
      name: 'Capacita\u00e7\u00e3o Profissional',
      description: 'Cursos de capacita\u00e7\u00e3o profissional em \u00e1reas como inform\u00e1tica, costura, culin\u00e1ria e atendimento.',
      status: ProjectStatus.ACTIVE,
      startDate: pastDate(60),
      endDate: futureDate(120),
      budget: 35000,
      raised: 20000,
      coordinator: 'Roberto Almeida',
      volunteerIds: [volunteerIds[3], volunteerIds[2]],
      goals: ['Formar 100 profissionais', 'Parceria com empresas locais', 'Encaminhar ao mercado de trabalho'],
      category: 'Capacita\u00e7\u00e3o',
      location: 'Sede da CUFA Pernambuco',
      beneficiaries: 100,
      createdAt: pastDate(60),
      updatedAt: pastDate(2),
    },
  ];

  // ---- Donations ----
  const donations: Donation[] = [
    {
      id: uuidv4(),
      donorId: donorIds[0],
      donorName: 'Empresa ABC Ltda',
      type: DonationType.FINANCIAL,
      amount: 10000,
      description: 'Doa\u00e7\u00e3o mensal corporativa',
      date: pastDate(5),
      projectId: projectIds[0],
      projectName: 'Educa\u00e7\u00e3o para Todos',
      receiptNumber: 'REC-2026-001',
      createdAt: pastDate(5),
      updatedAt: pastDate(5),
    },
    {
      id: uuidv4(),
      donorId: donorIds[1],
      donorName: 'Jo\u00e3o Silva',
      type: DonationType.FINANCIAL,
      amount: 500,
      description: 'Doa\u00e7\u00e3o pessoal via PIX',
      date: pastDate(10),
      receiptNumber: 'REC-2026-002',
      createdAt: pastDate(10),
      updatedAt: pastDate(10),
    },
    {
      id: uuidv4(),
      donorId: donorIds[2],
      donorName: 'Supermercado Esperan\u00e7a',
      type: DonationType.FOOD,
      description: 'Doa\u00e7\u00e3o de alimentos n\u00e3o perec\u00edveis',
      items: ['Arroz (50kg)', 'Feij\u00e3o (30kg)', 'Macarr\u00e3o (100 pacotes)', '\u00d3leo (20 litros)'],
      date: pastDate(15),
      projectId: projectIds[1],
      projectName: 'Sa\u00fade na Comunidade',
      createdAt: pastDate(15),
      updatedAt: pastDate(15),
    },
    {
      id: uuidv4(),
      donorId: donorIds[3],
      donorName: 'Funda\u00e7\u00e3o XYZ',
      type: DonationType.FINANCIAL,
      amount: 25000,
      description: 'Repasse semestral do edital de projetos sociais',
      date: pastDate(20),
      projectId: projectIds[1],
      projectName: 'Sa\u00fade na Comunidade',
      receiptNumber: 'REC-2026-003',
      createdAt: pastDate(20),
      updatedAt: pastDate(20),
    },
    {
      id: uuidv4(),
      donorId: donorIds[4],
      donorName: 'Maria Fernanda Costa',
      type: DonationType.MATERIAL,
      description: 'Doa\u00e7\u00e3o de material escolar',
      items: ['Cadernos (200 un)', 'L\u00e1pis (500 un)', 'Borrachas (300 un)', 'Mochilas (50 un)'],
      date: pastDate(25),
      projectId: projectIds[0],
      projectName: 'Educa\u00e7\u00e3o para Todos',
      createdAt: pastDate(25),
      updatedAt: pastDate(25),
    },
    {
      id: uuidv4(),
      donorId: donorIds[1],
      donorName: 'Jo\u00e3o Silva',
      type: DonationType.FINANCIAL,
      amount: 1000,
      description: 'Segunda doa\u00e7\u00e3o do m\u00eas',
      date: pastDate(3),
      receiptNumber: 'REC-2026-004',
      createdAt: pastDate(3),
      updatedAt: pastDate(3),
    },
    {
      id: uuidv4(),
      donorId: donorIds[5],
      donorName: 'Instituto Boa Vontade',
      type: DonationType.FINANCIAL,
      amount: 15000,
      description: 'Apoio ao programa de capacita\u00e7\u00e3o profissional',
      date: pastDate(35),
      projectId: projectIds[4],
      projectName: 'Capacita\u00e7\u00e3o Profissional',
      receiptNumber: 'REC-2026-005',
      createdAt: pastDate(35),
      updatedAt: pastDate(35),
    },
    {
      id: uuidv4(),
      donorId: donorIds[6],
      donorName: 'Farm\u00e1cia Popular',
      type: DonationType.MATERIAL,
      description: 'Doa\u00e7\u00e3o de medicamentos e material de primeiros socorros',
      items: ['Kit primeiros socorros (20)', 'Paracetamol (500 comprimidos)', 'Curativos (1000 un)'],
      date: pastDate(40),
      projectId: projectIds[1],
      projectName: 'Sa\u00fade na Comunidade',
      createdAt: pastDate(40),
      updatedAt: pastDate(40),
    },
    {
      id: uuidv4(),
      donorId: donorIds[4],
      donorName: 'Maria Fernanda Costa',
      type: DonationType.CLOTHING,
      description: 'Doa\u00e7\u00e3o de roupas infantis e adultas',
      items: ['Camisetas (100 un)', 'Cal\u00e7as (50 un)', 'Sapatos (30 pares)'],
      date: pastDate(12),
      createdAt: pastDate(12),
      updatedAt: pastDate(12),
    },
    {
      id: uuidv4(),
      donorId: donorIds[2],
      donorName: 'Supermercado Esperan\u00e7a',
      type: DonationType.FOOD,
      description: 'Segunda remessa de alimentos',
      items: ['Leite (200 litros)', 'A\u00e7\u00facar (100kg)', 'Caf\u00e9 (50kg)'],
      date: pastDate(8),
      createdAt: pastDate(8),
      updatedAt: pastDate(8),
    },
  ];

  // ---- Events ----
  const events: OngEvent[] = [
    {
      id: uuidv4(),
      name: 'Mutir\u00e3o de Limpeza',
      description: 'Dia de limpeza e conscientiza\u00e7\u00e3o ambiental na comunidade do Coque.',
      status: EventStatus.SCHEDULED,
      date: futureDate(15),
      startTime: '08:00',
      endTime: '12:00',
      location: 'Comunidade do Coque - Recife',
      maxParticipants: 50,
      participantIds: [volunteerIds[0], volunteerIds[2], volunteerIds[3]],
      category: 'Meio Ambiente',
      createdAt: pastDate(10),
      updatedAt: pastDate(10),
    },
    {
      id: uuidv4(),
      name: 'Feira de Sa\u00fade',
      description: 'Consultas m\u00e9dicas gratuitas, aferi\u00e7\u00e3o de press\u00e3o e orienta\u00e7\u00e3o nutricional.',
      status: EventStatus.SCHEDULED,
      date: futureDate(30),
      startTime: '09:00',
      endTime: '17:00',
      location: 'CUFA Pernambuco - Sede',
      maxParticipants: 100,
      participantIds: [volunteerIds[1], volunteerIds[4]],
      projectId: projectIds[1],
      projectName: 'Sa\u00fade na Comunidade',
      category: 'Sa\u00fade',
      createdAt: pastDate(8),
      updatedAt: pastDate(8),
    },
    {
      id: uuidv4(),
      name: 'Festival Junino Solid\u00e1rio',
      description: 'Festa junina beneficente com comidas t\u00edpicas e quadrilha. Renda revertida para projetos da CUFA.',
      status: EventStatus.SCHEDULED,
      date: futureDate(60),
      startTime: '18:00',
      endTime: '23:00',
      location: 'P\u00e1tio de S\u00e3o Pedro - Recife',
      maxParticipants: 200,
      participantIds: [volunteerIds[0], volunteerIds[2], volunteerIds[5], volunteerIds[6], volunteerIds[7]],
      category: 'Arrecada\u00e7\u00e3o',
      createdAt: pastDate(5),
      updatedAt: pastDate(5),
    },
    {
      id: uuidv4(),
      name: 'Palestra: Direitos Sociais',
      description: 'Palestra aberta sobre direitos sociais, trabalhistas e acesso a programas governamentais.',
      status: EventStatus.COMPLETED,
      date: pastDate(15),
      startTime: '19:00',
      endTime: '21:00',
      location: 'Audit\u00f3rio da Biblioteca Estadual - Recife',
      maxParticipants: 80,
      participantIds: [volunteerIds[0], volunteerIds[3], volunteerIds[4]],
      category: 'Educa\u00e7\u00e3o',
      createdAt: pastDate(45),
      updatedAt: pastDate(15),
    },
    {
      id: uuidv4(),
      name: 'Workshop de Inform\u00e1tica',
      description: 'Workshop introdut\u00f3rio de inform\u00e1tica b\u00e1sica para adultos.',
      status: EventStatus.SCHEDULED,
      date: futureDate(7),
      startTime: '14:00',
      endTime: '18:00',
      location: 'Laborat\u00f3rio de Inform\u00e1tica - CUFA PE',
      maxParticipants: 30,
      participantIds: [volunteerIds[2]],
      projectId: projectIds[4],
      projectName: 'Capacita\u00e7\u00e3o Profissional',
      category: 'Capacita\u00e7\u00e3o',
      createdAt: pastDate(3),
      updatedAt: pastDate(3),
    },
  ];

  // Write all data
  await writeCollection('users', users);
  await writeCollection('volunteers', volunteers);
  await writeCollection('donors', donors);
  await writeCollection('projects', projects);
  await writeCollection('donations', donations);
  await writeCollection('events', events);

  console.log('\u2705 Seed completed successfully!');
  console.log(`   - ${users.length} users`);
  console.log(`   - ${volunteers.length} volunteers`);
  console.log(`   - ${donors.length} donors`);
  console.log(`   - ${projects.length} projects`);
  console.log(`   - ${donations.length} donations`);
  console.log(`   - ${events.length} events`);
  console.log('\n\ud83d\udccb Default credentials:');
  console.log('   Admin:      admin@cufape.org.br / admin123');
  console.log('   Volunt\u00e1rio: maria@email.com / voluntario123');
  console.log('   Doador:     joao@email.com / doador123');
  console.log('   Visitante:  ana@email.com / visitante123');
}

// Run seed if called directly
seed().catch(console.error);
