// ============================================================
// Seed Script — Populates initial data for development
// ============================================================

import { v4 as uuidv4 } from 'uuid';
import { writeCollection } from './fileStore';
import { hashPassword } from './password';
import {
  User,
  UserRole,
  Volunteer,
  Project,
  ProjectStatus,
  Donation,
  DonationType,
  OngEvent,
  EventStatus,
} from '../models';

function pastDate(daysAgo: number): string {
  const d = new Date();
  d.setDate(d.getDate() - daysAgo);
  return d.toISOString();
}

function futureDate(daysAhead: number): string {
  const d = new Date();
  d.setDate(d.getDate() + daysAhead);
  return d.toISOString();
}

export async function seed(): Promise<void> {
  console.log('🌱 Seeding database...');

  // ---- Users ----
  const adminPassword = await hashPassword('admin123');
  const volunteerPassword = await hashPassword('voluntario123');
  const donorPassword = await hashPassword('doador123');

  const users: User[] = [
    {
      id: uuidv4(),
      name: 'Administrador',
      email: 'admin@wilsonaquino.org',
      password: adminPassword,
      role: UserRole.ADMIN,
      phone: '(11) 99999-0001',
      isActive: true,
      createdAt: pastDate(90),
      updatedAt: pastDate(90),
    },
    {
      id: uuidv4(),
      name: 'Maria Voluntária',
      email: 'maria@email.com',
      password: volunteerPassword,
      role: UserRole.VOLUNTEER,
      phone: '(11) 99999-0002',
      isActive: true,
      createdAt: pastDate(60),
      updatedAt: pastDate(60),
    },
    {
      id: uuidv4(),
      name: 'João Doador',
      email: 'joao@email.com',
      password: donorPassword,
      role: UserRole.DONOR,
      phone: '(11) 99999-0003',
      isActive: true,
      createdAt: pastDate(45),
      updatedAt: pastDate(45),
    },
    {
      id: uuidv4(),
      name: 'Ana Visitante',
      email: 'ana@email.com',
      password: await hashPassword('visitante123'),
      role: UserRole.VISITOR,
      phone: '(11) 99999-0004',
      isActive: true,
      createdAt: pastDate(30),
      updatedAt: pastDate(30),
    },
  ];

  // ---- Volunteers ----
  const volunteerIds = Array.from({ length: 8 }, () => uuidv4());
  const volunteers: Volunteer[] = [
    {
      id: volunteerIds[0],
      name: 'Maria Silva Santos',
      email: 'maria.silva@email.com',
      phone: '(11) 98765-1001',
      cpf: '123.456.789-01',
      birthDate: '1990-05-15',
      address: 'Rua das Flores, 123',
      city: 'São Paulo',
      state: 'SP',
      zipCode: '01234-567',
      skills: ['Educação', 'Comunicação', 'Liderança'],
      availability: 'Fins de semana',
      notes: 'Professora aposentada',
      isActive: true,
      createdAt: pastDate(80),
      updatedAt: pastDate(80),
    },
    {
      id: volunteerIds[1],
      name: 'Carlos Eduardo Lima',
      email: 'carlos.lima@email.com',
      phone: '(11) 98765-1002',
      cpf: '234.567.890-12',
      birthDate: '1985-08-22',
      address: 'Av. Brasil, 456',
      city: 'São Paulo',
      state: 'SP',
      zipCode: '02345-678',
      skills: ['Saúde', 'Primeiros socorros'],
      availability: 'Segundas e quartas',
      isActive: true,
      createdAt: pastDate(70),
      updatedAt: pastDate(70),
    },
    {
      id: volunteerIds[2],
      name: 'Fernanda Oliveira',
      email: 'fernanda.o@email.com',
      phone: '(11) 98765-1003',
      cpf: '345.678.901-23',
      birthDate: '1995-12-03',
      address: 'Rua Esperança, 789',
      city: 'São Paulo',
      state: 'SP',
      zipCode: '03456-789',
      skills: ['Tecnologia', 'Design', 'Redes sociais'],
      availability: 'Integral',
      isActive: true,
      createdAt: pastDate(60),
      updatedAt: pastDate(60),
    },
    {
      id: volunteerIds[3],
      name: 'Roberto Almeida',
      email: 'roberto.a@email.com',
      phone: '(11) 98765-1004',
      cpf: '456.789.012-34',
      birthDate: '1988-03-17',
      address: 'Rua da Paz, 321',
      city: 'Guarulhos',
      state: 'SP',
      zipCode: '04567-890',
      skills: ['Logística', 'Transporte', 'Organização'],
      availability: 'Fins de semana',
      isActive: true,
      createdAt: pastDate(50),
      updatedAt: pastDate(50),
    },
    {
      id: volunteerIds[4],
      name: 'Juliana Costa',
      email: 'juliana.c@email.com',
      phone: '(11) 98765-1005',
      cpf: '567.890.123-45',
      birthDate: '1992-07-28',
      address: 'Rua Alegria, 654',
      city: 'Osasco',
      state: 'SP',
      zipCode: '05678-901',
      skills: ['Psicologia', 'Atendimento'],
      availability: 'Terças e quintas',
      isActive: true,
      createdAt: pastDate(40),
      updatedAt: pastDate(40),
    },
    {
      id: volunteerIds[5],
      name: 'Pedro Henrique Souza',
      email: 'pedro.h@email.com',
      phone: '(21) 98765-1006',
      cpf: '678.901.234-56',
      birthDate: '1993-11-09',
      address: 'Av. Liberdade, 987',
      city: 'Rio de Janeiro',
      state: 'RJ',
      zipCode: '06789-012',
      skills: ['Esportes', 'Recreação'],
      availability: 'Sábados',
      isActive: true,
      createdAt: pastDate(30),
      updatedAt: pastDate(30),
    },
    {
      id: volunteerIds[6],
      name: 'Luciana Ferreira',
      email: 'luciana.f@email.com',
      phone: '(11) 98765-1007',
      cpf: '789.012.345-67',
      birthDate: '1987-01-25',
      address: 'Rua Harmonia, 159',
      city: 'São Paulo',
      state: 'SP',
      zipCode: '07890-123',
      skills: ['Culinária', 'Nutrição'],
      availability: 'Quintas e sextas',
      isActive: false,
      createdAt: pastDate(20),
      updatedAt: pastDate(10),
    },
    {
      id: volunteerIds[7],
      name: 'Marcos Antonio Torres',
      email: 'marcos.t@email.com',
      phone: '(11) 98765-1008',
      cpf: '890.123.456-78',
      birthDate: '1991-06-14',
      address: 'Rua Progresso, 753',
      city: 'São Paulo',
      state: 'SP',
      zipCode: '08901-234',
      skills: ['Construção', 'Elétrica', 'Hidráulica'],
      availability: 'Domingos',
      isActive: true,
      createdAt: pastDate(15),
      updatedAt: pastDate(15),
    },
  ];

  // ---- Projects ----
  const projectIds = Array.from({ length: 5 }, () => uuidv4());
  const projects: Project[] = [
    {
      id: projectIds[0],
      name: 'Educação para Todos',
      description: 'Programa de reforço escolar e alfabetização para crianças e adultos da comunidade, com aulas de português, matemática e ciências.',
      status: ProjectStatus.ACTIVE,
      startDate: pastDate(120),
      endDate: futureDate(240),
      budget: 50000,
      raised: 35000,
      coordinator: 'Maria Silva Santos',
      volunteerIds: [volunteerIds[0], volunteerIds[2], volunteerIds[4]],
      goals: ['Alfabetizar 100 adultos', 'Reforço escolar para 200 crianças', 'Formar 20 monitores'],
      category: 'Educação',
      location: 'Centro Comunitário Vila Esperança',
      beneficiaries: 300,
      createdAt: pastDate(120),
      updatedAt: pastDate(5),
    },
    {
      id: projectIds[1],
      name: 'Saúde na Comunidade',
      description: 'Ações preventivas de saúde incluindo consultas médicas, vacinação e orientação sobre higiene e alimentação saudável.',
      status: ProjectStatus.ACTIVE,
      startDate: pastDate(90),
      endDate: futureDate(180),
      budget: 80000,
      raised: 55000,
      coordinator: 'Carlos Eduardo Lima',
      volunteerIds: [volunteerIds[1], volunteerIds[4]],
      goals: ['Atender 500 consultas', 'Campanha de vacinação', 'Palestras sobre saúde preventiva'],
      category: 'Saúde',
      location: 'Posto de Saúde Comunitário',
      beneficiaries: 500,
      createdAt: pastDate(90),
      updatedAt: pastDate(3),
    },
    {
      id: projectIds[2],
      name: 'Horta Comunitária',
      description: 'Criação e manutenção de hortas comunitárias para promover alimentação saudável e geração de renda.',
      status: ProjectStatus.PLANNING,
      startDate: futureDate(30),
      budget: 15000,
      raised: 8000,
      coordinator: 'Fernanda Oliveira',
      volunteerIds: [volunteerIds[2], volunteerIds[6]],
      goals: ['Implantar 3 hortas comunitárias', 'Capacitar 50 famílias', 'Venda de excedentes'],
      category: 'Meio Ambiente',
      location: 'Terrenos comunitários',
      beneficiaries: 150,
      createdAt: pastDate(30),
      updatedAt: pastDate(1),
    },
    {
      id: projectIds[3],
      name: 'Esporte para Vida',
      description: 'Programa esportivo para jovens em situação de vulnerabilidade social, incluindo futebol, vôlei e artes marciais.',
      status: ProjectStatus.COMPLETED,
      startDate: pastDate(365),
      endDate: pastDate(30),
      budget: 40000,
      raised: 40000,
      coordinator: 'Pedro Henrique Souza',
      volunteerIds: [volunteerIds[5], volunteerIds[7]],
      goals: ['Atender 200 jovens', 'Torneio municipal', 'Bolsas esportivas'],
      category: 'Esporte',
      location: 'Ginásio Municipal',
      beneficiaries: 200,
      createdAt: pastDate(365),
      updatedAt: pastDate(30),
    },
    {
      id: projectIds[4],
      name: 'Capacitação Profissional',
      description: 'Cursos de capacitação profissional em áreas como informática, costura, culinária e atendimento ao cliente.',
      status: ProjectStatus.ACTIVE,
      startDate: pastDate(60),
      endDate: futureDate(120),
      budget: 35000,
      raised: 20000,
      coordinator: 'Roberto Almeida',
      volunteerIds: [volunteerIds[3], volunteerIds[2]],
      goals: ['Formar 100 profissionais', 'Parceria com empresas locais', 'Encaminhar ao mercado de trabalho'],
      category: 'Capacitação',
      location: 'Sede da ONG Wilson Aquino',
      beneficiaries: 100,
      createdAt: pastDate(60),
      updatedAt: pastDate(2),
    },
  ];

  // ---- Donations ----
  const donations: Donation[] = [
    {
      id: uuidv4(),
      donorId: 'donor-001',
      donorName: 'Empresa ABC Ltda',
      type: DonationType.FINANCIAL,
      amount: 10000,
      description: 'Doação mensal corporativa',
      date: pastDate(5),
      projectId: projectIds[0],
      projectName: 'Educação para Todos',
      receiptNumber: 'REC-2026-001',
      createdAt: pastDate(5),
      updatedAt: pastDate(5),
    },
    {
      id: uuidv4(),
      donorId: 'donor-002',
      donorName: 'João Silva',
      type: DonationType.FINANCIAL,
      amount: 500,
      description: 'Doação pessoal via PIX',
      date: pastDate(10),
      receiptNumber: 'REC-2026-002',
      createdAt: pastDate(10),
      updatedAt: pastDate(10),
    },
    {
      id: uuidv4(),
      donorId: 'donor-003',
      donorName: 'Supermercado Esperança',
      type: DonationType.MATERIAL,
      description: 'Doação de alimentos não perecíveis',
      items: ['Arroz (50kg)', 'Feijão (30kg)', 'Macarrão (100 pacotes)', 'Óleo (20 litros)'],
      date: pastDate(15),
      projectId: projectIds[1],
      projectName: 'Saúde na Comunidade',
      createdAt: pastDate(15),
      updatedAt: pastDate(15),
    },
    {
      id: uuidv4(),
      donorId: 'donor-004',
      donorName: 'Fundação XYZ',
      type: DonationType.FINANCIAL,
      amount: 25000,
      description: 'Repasse semestral do edital de projetos sociais',
      date: pastDate(20),
      projectId: projectIds[1],
      projectName: 'Saúde na Comunidade',
      receiptNumber: 'REC-2026-003',
      createdAt: pastDate(20),
      updatedAt: pastDate(20),
    },
    {
      id: uuidv4(),
      donorId: 'donor-005',
      donorName: 'Maria Fernanda Costa',
      type: DonationType.MATERIAL,
      description: 'Doação de material escolar',
      items: ['Cadernos (200 unidades)', 'Lápis (500 unidades)', 'Borrachas (300 unidades)', 'Mochilas (50 unidades)'],
      date: pastDate(25),
      projectId: projectIds[0],
      projectName: 'Educação para Todos',
      createdAt: pastDate(25),
      updatedAt: pastDate(25),
    },
    {
      id: uuidv4(),
      donorId: 'donor-002',
      donorName: 'João Silva',
      type: DonationType.FINANCIAL,
      amount: 1000,
      description: 'Segunda doação do mês',
      date: pastDate(3),
      receiptNumber: 'REC-2026-004',
      createdAt: pastDate(3),
      updatedAt: pastDate(3),
    },
    {
      id: uuidv4(),
      donorId: 'donor-006',
      donorName: 'Instituto Boa Vontade',
      type: DonationType.FINANCIAL,
      amount: 15000,
      description: 'Apoio ao programa de capacitação profissional',
      date: pastDate(35),
      projectId: projectIds[4],
      projectName: 'Capacitação Profissional',
      receiptNumber: 'REC-2026-005',
      createdAt: pastDate(35),
      updatedAt: pastDate(35),
    },
    {
      id: uuidv4(),
      donorId: 'donor-007',
      donorName: 'Farmácia Popular',
      type: DonationType.MATERIAL,
      description: 'Doação de medicamentos e material de primeiros socorros',
      items: ['Kit primeiros socorros (20)', 'Paracetamol (500 comprimidos)', 'Curativos (1000 unidades)'],
      date: pastDate(40),
      projectId: projectIds[1],
      projectName: 'Saúde na Comunidade',
      createdAt: pastDate(40),
      updatedAt: pastDate(40),
    },
  ];

  // ---- Events ----
  const events: OngEvent[] = [
    {
      id: uuidv4(),
      name: 'Mutirão de Limpeza',
      description: 'Dia de limpeza e conscientização ambiental na comunidade Vila Esperança, com coleta seletiva e plantio de árvores.',
      status: EventStatus.SCHEDULED,
      date: futureDate(15),
      startTime: '08:00',
      endTime: '12:00',
      location: 'Praça Central - Vila Esperança',
      maxParticipants: 50,
      participantIds: [volunteerIds[0], volunteerIds[2], volunteerIds[3]],
      category: 'Meio Ambiente',
      createdAt: pastDate(10),
      updatedAt: pastDate(10),
    },
    {
      id: uuidv4(),
      name: 'Feira de Saúde',
      description: 'Evento com consultas médicas gratuitas, aferição de pressão, teste de glicemia e orientação nutricional.',
      status: EventStatus.SCHEDULED,
      date: futureDate(30),
      startTime: '09:00',
      endTime: '17:00',
      location: 'Ginásio Municipal',
      maxParticipants: 100,
      participantIds: [volunteerIds[1], volunteerIds[4]],
      projectId: projectIds[1],
      projectName: 'Saúde na Comunidade',
      category: 'Saúde',
      createdAt: pastDate(8),
      updatedAt: pastDate(8),
    },
    {
      id: uuidv4(),
      name: 'Festival Junino Solidário',
      description: 'Festa junina beneficente com comidas típicas, quadrilha e brincadeiras. Toda renda será revertida para os projetos da ONG.',
      status: EventStatus.SCHEDULED,
      date: futureDate(60),
      startTime: '18:00',
      endTime: '23:00',
      location: 'Sede da ONG Wilson Aquino',
      maxParticipants: 200,
      participantIds: [volunteerIds[0], volunteerIds[2], volunteerIds[5], volunteerIds[6], volunteerIds[7]],
      category: 'Arrecadação',
      createdAt: pastDate(5),
      updatedAt: pastDate(5),
    },
    {
      id: uuidv4(),
      name: 'Palestra: Direitos Sociais',
      description: 'Palestra aberta sobre direitos sociais, trabalhistas e acesso a programas governamentais.',
      status: EventStatus.COMPLETED,
      date: pastDate(15),
      startTime: '19:00',
      endTime: '21:00',
      location: 'Auditório Biblioteca Municipal',
      maxParticipants: 80,
      participantIds: [volunteerIds[0], volunteerIds[3], volunteerIds[4]],
      category: 'Educação',
      createdAt: pastDate(45),
      updatedAt: pastDate(15),
    },
    {
      id: uuidv4(),
      name: 'Workshop de Informática',
      description: 'Workshop introdutório de informática básica para adultos, incluindo uso de computador, internet e ferramentas de escritório.',
      status: EventStatus.SCHEDULED,
      date: futureDate(7),
      startTime: '14:00',
      endTime: '18:00',
      location: 'Laboratório de Informática - Sede',
      maxParticipants: 30,
      participantIds: [volunteerIds[2]],
      projectId: projectIds[4],
      projectName: 'Capacitação Profissional',
      category: 'Capacitação',
      createdAt: pastDate(3),
      updatedAt: pastDate(3),
    },
  ];

  // Write all data
  await writeCollection('users', users);
  await writeCollection('volunteers', volunteers);
  await writeCollection('projects', projects);
  await writeCollection('donations', donations);
  await writeCollection('events', events);

  console.log('✅ Seed completed successfully!');
  console.log(`   - ${users.length} users`);
  console.log(`   - ${volunteers.length} volunteers`);
  console.log(`   - ${projects.length} projects`);
  console.log(`   - ${donations.length} donations`);
  console.log(`   - ${events.length} events`);
  console.log('\n📋 Default credentials:');
  console.log('   Admin:      admin@wilsonaquino.org / admin123');
  console.log('   Voluntário: maria@email.com / voluntario123');
  console.log('   Doador:     joao@email.com / doador123');
  console.log('   Visitante:  ana@email.com / visitante123');
}

// Run seed if called directly
seed().catch(console.error);
